/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1b1b1b",
        outline: "#8b90a0",
        secondary: "#aec6ff",
        "on-secondary-container": "#00275e",
        "on-primary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#5d5f5f",
        "on-background": "#e2e2e2",
        background: "#131313",
        "surface-dim": "#131313",
        surface: "#131313",
        "secondary-container": "#508eff",
        "on-tertiary-container": "#ffffff",
        "surface-variant": "#353535",
        "on-secondary-fixed": "#001a43",
        "tertiary-container": "#dd3438",
        "on-surface-variant": "#c1c6d7",
        "outline-variant": "#414754",
        "on-secondary": "#002e6b",
        "inverse-surface": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#004397",
        "surface-container-highest": "#353535",
        "surface-container": "#1f1f1f",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary": "#68000b",
        "inverse-on-surface": "#303030",
        "on-primary-fixed": "#1a1c1c",
        "surface-bright": "#393939",
        "primary-container": "#757676",
        error: "#ffb4ab",
        "on-surface": "#e2e2e2",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#aec6ff",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#c6c6c7",
        "error-container": "#93000a",
        "surface-tint": "#c6c6c7",
        "on-primary": "#2f3131",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#930014",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed-dim": "#ffb3ae",
        primary: "#c6c6c7",
        tertiary: "#ffb3ae",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#410004",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
}
